[package]
name = "crondes"
version = "0.1.0"
edition = "2024"

[dependencies]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[build-dependencies]

[features]
default = []

[lib]
crate-type = ["staticlib", "rlib"]
